version: 2
jobs:
  build:
    docker:
      - image: nijohando/circleci-clj
    environment:
      - CLJCMD: clojure
    steps:
      - checkout
      - restore_cache:
          keys:
            - m2-{{ checksum "deps.edn" }}
            - m2-
      - run: make test-clj
      - run: make test-cljs
      - save_cache:
          key: m2-{{ checksum "deps.edn" }}
          paths:
            - ~/.m2
